const HTTP_STATUS_CODE = {
  // SUCCESSES
  CREATED: 201,
  SUCCESS: 200,
  NO_CONTENT: 204,

  // ERRORS
  BAD_REQUEST: 400,
  FORBIDDEN_ACCESS: 403,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
}

export { HTTP_STATUS_CODE }
